### ISSUE TITLE
De-orphaning bit?

### ISSUE THREAD

**Issue by schuemie** [truecluster/bit#1]
Ever since bit was declared ORPHANED on CRAN, CRAN has rejected any package or package update that depends on bit. Would it be possible to de-orphan bit temporarily to give us some time to move away from bit?

**Comment by agrueneberg** [comment]
Why is this package orphaned in the first place considering that @truecluster is actively working on it at the moment? I'm also having trouble submitting updates for some of my packages.

**Comment by truecluster** [comment]
I hope that CRAN accepts my submittal at beginning of June.
